# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
   inputs:
      input:
        description: "Execute CI/CD"
        required: false
        default: "Execute CI/CD manually"

env:
  BASE_PATH: ./src/
  
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: |
        cd ${{ env.BASE_PATH }}
        dotnet restore pocapi.sln

    - name: Build
      run: | 
        cd ${{ env.BASE_PATH }}
        dotnet build pocapi.sln --no-restore
      
    - name: Test
      run: |
        cd ${{ env.BASE_PATH }}
        dotnet test ../tests/ApplicationTests/ApplicationTests.csproj --no-build --verbosity normal
    
